AWSTemplateFormatVersion : '2010-09-09'

Resources:
    MyBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        Properties:
            BucketName: my-unique-s3-bucket-name2333
